//Show Quran
export const SHOW_QURAN = "SHOW_QURAN ";
export const GET_SURAH_DATA = "GET_SURAH_DATA";
export const WITHOUT_CLICK = "WITHOUT_CLICK";
export const SHOW_QURAN_CHAPTER_WISE = "SHOW_QURAN_CHAPTER_WISE";
export const SET_QURAN_PAGE = "SET_QURAN_PAGE";
export const INITIALIZE_QURAN = "INITIALIZE_QURAN";
export const MARK_AYAH = "MARK_AYAH";
export const MARK_PAGE_MISTAKE = "MARK_PAGE_MISTAKE";
export const JUZ_LIST = "JUZ_LIST";
export const CHAPTER_LIST = "CHAPTER_LIST";
//teacher
export const TEACHER_LOGIN = "TEACHER_LOGIN";
export const TEACHER_SIGNUP = "TEACHER_SIGNUP";
export const TEACHER_REQUEST_RESPONSE = "TEACHER_REQUEST_RESPONSE";
export const STUDENT_REQUEST_STATUS = "STUDENT_REQUEST_STATUS";
export const TEACHER_STUDENTS_LIST = "TEACHER_STUDENTS_LIST";
export const TEACHER_FRIENDS_PROFILE = "TEACHER_STUDENTS_PROFILE";
export const CREATE_NEW_GROUP = "CREATE_NEW_GROUP";
export const TEACHER_CREATED_GROUPS_LIST = "TEACHER_CREATED_GROUPS_LIST";
export const ADD_STUDENT_TO_GROUP = "ADD_STUDENT_TO_GROUP";
export const BACK_FROM_HOME_SCREEN = "BACK_FROM_HOME_SCREEN";
export const LIST_OF_STUDENT_IN_GROUP = "LIST_OF_STUDENT_IN_GROUP";
export const STUDENT_NOT_IN_GROUP = "STUDENT_NOT_IN_GROUP";
export const TEACHER_FRIENDS_PROFILE1 = "TEACHER_FRIENDS_PROFILE1";
export const STUDENT_ID = "STUDENT_ID";
//Mistak
export const ISSUE_MISTAK_BY_TEACHER = "ISSUE_MISTAK_BY_TEACHER";
export const UPDATE_MISTAK_BY_TEACHER = "UPDATE_MISTAK_BY_TEACHER";

//student
export const STUDENT_SIGNUP = "STUDENT_SIGNUP";
export const STUDENT_LOGIN = "STUDENT_LOGIN";
export const STUDENT_REQUEST_TEACHER = "STUDENT_REQUEST_TEACHER";
export const SEARCH_TEACHER = "SEARCH_TEACHER";
export const GET_STUDENT_PROFILE = "GET_STUDENT_PROFILE";
export const STUDENT_MISTAKE_BY_STATUS = "STUDENT_MISTAKE_BY_STATUS";
export const STUDENT_MISTAKE_BY_CHAPTER = "STUDENT_MISTAKE_BY_CHAPTER";

export const INIT_QURAN_CONTEXT = "INIT_QURAN_CONTEXT";
